const path = 'https://www.amcharts.com/wp-content/themes/amcharts4/css/img/icons/weather/animated/';
const localPath = '../img/icons/';
const weatherIcons = {
    c01d: `${path}day.svg`,
    c01n: `${localPath}c01n.png`,
    c02d: `${path}cloudy-day-1.svg`,
    c02n: `${path}cloudy-night-1.svg`,
    c03d: `${path}cloudy-day-3.svg`,
    c03n: `${path}cloudy-night-3.svg`,
    c04d: `${path}cloudy.svg`,
    c04n: `${path}cloudy.svg`,
    t01d: `${path}thunder.svg`,
    t01n: `${localPath}t01n.png`,
    t02d: `${path}thunder.svg`,
    t02n: `${localPath}t02n.png`,
    t03d: `${path}thunder.svg`,
    t03n: `${localPath}t03n.png`,
    t04d: `${path}thunder.svg`,
    t04n: `${localPath}t04n.png`,
    t05d: `${path}.svg`,
    t05n: `${localPath}t05n.png`,
    d01d: `${path}rainy-4.svg`,
    d01n: `${path}rainy-4.svg`,
    d02d: `${path}rainy-4.svg`,
    d02n: `${path}rainy-4.svg`,
    d03d: `${path}rainy-7.svg`,
    d03n: `${path}rainy-7.svg`,
    r01d: `${path}rainy-5.svg`,
    r01n: `${path}rainy-5.svg`,
    r02d: `${path}rainy-5.svg`,
    r02n: `${path}rainy-5.svg`,
    r03d: `${path}rainy-6.svg`,
    r03n: `${path}rainy-6.svg`,
    f01d: `${path}rainy-6.svg`,
    f01n: `${path}rainy-6.svg`,
    r04d: `${path}rainy-5.svg`,
    r04n: `${path}rainy-5.svg`,
    r05d: `${path}rainy-2.svg`,
    r05n: `${localPath}r05n.png`,
    r06d: `${path}rainy-3.svg`,
    r06n: `${localPath}r06n.png`,
    s01d: `${path}snowy-4.svg`,
    s01n: `${path}snowy-4.svg`,
    s02d: `${path}snowy-5.svg`,
    s02n: `${path}snowy-5.svg`,
    s03d: `${path}snowy-6.svg`,
    s03n: `${path}snowy-6.svg`,
    s04d: `${path}snowy-1.svg`,
    s04n: `${localPath}s04n.png`,
    s05d: `${localPath}s05d.png`,
    s05n: `${localPath}s05n.png`,
    s06d: `${localPath}s06d.png`,
    s06n: `${localPath}s06n.png`,
    a01d: `${localPath}a01d.png`,
    a01n: `${localPath}a01n.png`,
    a02d: `${localPath}a02d.png`,
    a02n: `${localPath}a02n.png`,
    a03d: `${localPath}a03d.png`,
    a03n: `${localPath}a03n.png`,
    a04d: `${localPath}a04d.png`,
    a04n: `${localPath}a04n.png`,
    a05d: `${localPath}a05d.png`,
    a05n: `${localPath}s05n.png`,
    a06d: `${localPath}a06d.png`,
    a06n: `${localPath}a06n.png`,
    u00d: `${localPath}u00d.png`,
    u00n: `${localPath}u00n.png`,

};

export { weatherIcons };